---
kind: Service
apiVersion: v1
metadata:
  name: gobgp
spec:
  selector:
    app: gobgp
  ports:
  - protocol: TCP
    port: 179
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: gobgp
  labels:
    app: gobgp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gobgp
  template:
    metadata:
      labels:
        app: gobgp
    spec:
      tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
      - name: gobgp
        image: cengn/gobgp:v1.3
---
