---
apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  selector:
    app: elasticsearch
  type: NodePort
  ports:
  - name: ntw
    protocol: TCP
    port: 15555
    targetPort: 9376
  - name: skyw
    protocol: TCP
    port: 25555
    targetPort: 9377
  - name: bespin
    protocol: TCP
    port: 35555
    targetPort: 9378
  - name: infra
    protocol: TCP
    port: 45555
    targetPort: 9379
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: "logstash"
        image: docker.elastic.co/logstash/logstash-oss:6.1.1
